version: '3.8'

services:
  zivvochat-server:
    image: zivvochat/server:latest
    build:
      context: .
      target: server-runtime
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    networks:
      - zivvochat-network

  zivvochat-frontend:
    image: zivvochat/frontend:latest
    build:
      context: .
      target: frontend-runtime
    ports:
      - "3000:3000"
    depends_on:
      - zivvochat-server
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_SOCKET_URL=http://localhost:5000
      - NEXT_PUBLIC_API_URL=http://localhost:5000/api
    networks:
      - zivvochat-network

networks:
  zivvochat-network:
    driver: bridge